-- pgvector: required by cases.embedding (added manually; drizzle-kit does not
-- emit extension creation). Safe/idempotent.
CREATE EXTENSION IF NOT EXISTS vector;--> statement-breakpoint
CREATE TYPE "public"."assignment_status" AS ENUM('active', 'completed', 'transferred', 'escalated', 'cancelled', 'on_hold');--> statement-breakpoint
CREATE TYPE "public"."assignment_type" AS ENUM('primary', 'secondary', 'reviewer', 'escalated', 'temporary', 'collaborative');--> statement-breakpoint
CREATE TYPE "public"."attachment_category" AS ENUM('evidence', 'correspondence', 'resolution', 'support', 'identity');--> statement-breakpoint
CREATE TYPE "public"."attachment_type" AS ENUM('document', 'image', 'audio', 'video', 'other');--> statement-breakpoint
CREATE TYPE "public"."audit_action" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'ASSIGN', 'TRANSFER', 'ESCALATE', 'RESOLVE', 'COMMENT', 'ATTACH', 'VIEW', 'EXPORT', 'SYSTEM_INIT');--> statement-breakpoint
CREATE TYPE "public"."audit_entity_type" AS ENUM('case', 'user', 'comment', 'attachment', 'assignment', 'notification', 'setting', 'session', 'system');--> statement-breakpoint
CREATE TYPE "public"."case_history_action_type" AS ENUM('CREATION', 'STATUS_CHANGE', 'ASSIGNMENT_CHANGE', 'PRIORITY_CHANGE', 'CATEGORY_CHANGE', 'UPDATE', 'COMMENT_ADDED', 'ESCALATION', 'RESOLUTION');--> statement-breakpoint
CREATE TYPE "public"."comment_type" AS ENUM('internal', 'external', 'resolution', 'escalation', 'follow_up', 'status_update', 'assignment');--> statement-breakpoint
CREATE TYPE "public"."communication_method" AS ENUM('email', 'phone', 'in_person', 'system', 'sms', 'video_call');--> statement-breakpoint
CREATE TYPE "public"."communication_status" AS ENUM('sent', 'delivered', 'read', 'failed', 'pending');--> statement-breakpoint
CREATE TYPE "public"."confidentiality_level" AS ENUM('public', 'internal', 'restricted', 'confidential');--> statement-breakpoint
CREATE TYPE "public"."encryption_status" AS ENUM('none', 'encrypted', 'password_protected');--> statement-breakpoint
CREATE TYPE "public"."environment" AS ENUM('development', 'staging', 'production', 'all');--> statement-breakpoint
CREATE TYPE "public"."follow_up_contact_method" AS ENUM('email', 'phone', 'in_person', 'sms', 'none');--> statement-breakpoint
CREATE TYPE "public"."notification_entity_type" AS ENUM('case', 'user', 'assignment', 'comment', 'attachment');--> statement-breakpoint
CREATE TYPE "public"."notification_priority" AS ENUM('low', 'normal', 'high', 'urgent');--> statement-breakpoint
CREATE TYPE "public"."notification_type" AS ENUM('case_assigned', 'case_updated', 'case_status_changed', 'comment_added', 'escalation', 'due_date_reminder', 'case_resolved', 'assignment_transferred', 'quality_review_required');--> statement-breakpoint
CREATE TYPE "public"."provider_age_group" AS ENUM('under_18', '18_25', '26_35', '36_50', '51_65', 'over_65');--> statement-breakpoint
CREATE TYPE "public"."provider_disability_status" AS ENUM('none', 'physical', 'visual', 'hearing', 'cognitive', 'multiple', 'prefer_not_to_say');--> statement-breakpoint
CREATE TYPE "public"."provider_gender" AS ENUM('male', 'female', 'other', 'prefer_not_to_say');--> statement-breakpoint
CREATE TYPE "public"."recipient_type" AS ENUM('case_provider', 'team_member', 'manager', 'external_partner', 'system');--> statement-breakpoint
CREATE TYPE "public"."request_method" AS ENUM('GET', 'POST', 'PUT', 'DELETE', 'PATCH');--> statement-breakpoint
CREATE TYPE "public"."resolution_category" AS ENUM('resolved', 'closed_no_action', 'referred', 'duplicate', 'withdrawn');--> statement-breakpoint
CREATE TYPE "public"."resolution_satisfaction" AS ENUM('very_satisfied', 'satisfied', 'neutral', 'dissatisfied', 'very_dissatisfied');--> statement-breakpoint
CREATE TYPE "public"."session_type" AS ENUM('web', 'mobile', 'api', 'admin');--> statement-breakpoint
CREATE TYPE "public"."setting_category" AS ENUM('email', 'notification', 'sla', 'security', 'ui', 'integration', 'general');--> statement-breakpoint
CREATE TYPE "public"."setting_type" AS ENUM('string', 'number', 'boolean', 'json', 'encrypted');--> statement-breakpoint
CREATE TYPE "public"."storage_provider" AS ENUM('local', 'b2', 'azure', 'aws', 'google', 'onedrive');--> statement-breakpoint
CREATE TYPE "public"."urgency_level" AS ENUM('low', 'medium', 'high', 'critical');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('user', 'staff', 'manager', 'admin', 'super_admin');--> statement-breakpoint
CREATE TYPE "public"."virus_scan_status" AS ENUM('pending', 'clean', 'infected', 'quarantined', 'failed', 'skipped');--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(50) NOT NULL,
	"email" varchar(100) NOT NULL,
	"password" varchar(255) NOT NULL,
	"first_name" varchar(50) NOT NULL,
	"last_name" varchar(50) NOT NULL,
	"profile_picture" varchar(512),
	"bio" varchar(500),
	"date_of_birth" date,
	"phone" varchar(20),
	"address" varchar(255),
	"city" varchar(100),
	"state" varchar(100),
	"country" varchar(100),
	"postal_code" varchar(20),
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"organization" varchar(100),
	"is_active" boolean DEFAULT true NOT NULL,
	"is_online" boolean DEFAULT false NOT NULL,
	"last_login" timestamp with time zone,
	"is_email_verified" boolean DEFAULT false NOT NULL,
	"email_verified_at" timestamp with time zone,
	"email_verification_token" varchar(255),
	"email_verification_expires" timestamp with time zone,
	"two_factor_enabled" boolean DEFAULT false NOT NULL,
	"two_factor_secret" varchar(255),
	"login_attempts" integer DEFAULT 0 NOT NULL,
	"lock_until" timestamp with time zone,
	"password_changed_at" timestamp with time zone,
	"password_reset_token" varchar(255),
	"password_reset_expires" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" integer,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "case_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "case_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"arabic_name" varchar(100),
	"description" varchar(500),
	"arabic_description" varchar(500),
	"icon" varchar(50),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"color" varchar(20),
	CONSTRAINT "case_categories_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "case_channels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "case_channels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"arabic_name" varchar(100),
	"description" varchar(500),
	"arabic_description" varchar(500),
	"icon" varchar(50),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"color" varchar(20),
	CONSTRAINT "case_channels_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "case_priorities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "case_priorities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"arabic_name" varchar(100),
	"description" varchar(500),
	"arabic_description" varchar(500),
	"icon" varchar(50),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"color" varchar(20) NOT NULL,
	"level" integer NOT NULL,
	"response_time_hours" integer,
	"resolution_time_hours" integer,
	"escalation_time_hours" integer,
	CONSTRAINT "case_priorities_name_unique" UNIQUE("name"),
	CONSTRAINT "case_priorities_level_unique" UNIQUE("level")
);
--> statement-breakpoint
CREATE TABLE "case_statuses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "case_statuses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"arabic_name" varchar(100),
	"description" varchar(500),
	"arabic_description" varchar(500),
	"icon" varchar(50),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"color" varchar(20) NOT NULL,
	"is_initial" boolean DEFAULT false NOT NULL,
	"is_final" boolean DEFAULT false NOT NULL,
	"allow_reopen" boolean DEFAULT true NOT NULL,
	CONSTRAINT "case_statuses_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "provider_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provider_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"arabic_name" varchar(100),
	"description" varchar(500),
	"arabic_description" varchar(500),
	"icon" varchar(50),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"color" varchar(20),
	CONSTRAINT "provider_types_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "communities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "communities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"arabic_name" varchar(100),
	"code" varchar(10),
	"description" varchar(500),
	"arabic_description" varchar(500),
	"governorate_id" integer NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	CONSTRAINT "uq_communities_governorate_name" UNIQUE("governorate_id","name")
);
--> statement-breakpoint
CREATE TABLE "governorates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "governorates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"arabic_name" varchar(100),
	"code" varchar(10) NOT NULL,
	"description" varchar(500),
	"arabic_description" varchar(500),
	"region_id" integer NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	CONSTRAINT "uq_governorates_region_name" UNIQUE("region_id","name"),
	CONSTRAINT "uq_governorates_region_code" UNIQUE("region_id","code")
);
--> statement-breakpoint
CREATE TABLE "regions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "regions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"arabic_name" varchar(100),
	"code" varchar(10) NOT NULL,
	"description" varchar(500),
	"arabic_description" varchar(500),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	CONSTRAINT "regions_name_unique" UNIQUE("name"),
	CONSTRAINT "regions_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "activities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"arabic_name" varchar(200),
	"code" varchar(20) NOT NULL,
	"description" varchar(1000),
	"arabic_description" varchar(1000),
	"project_id" integer,
	"color" varchar(20),
	"icon" varchar(50),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	CONSTRAINT "uq_activities_project_name" UNIQUE("project_id","name"),
	CONSTRAINT "uq_activities_project_code" UNIQUE("project_id","code")
);
--> statement-breakpoint
CREATE TABLE "programs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "programs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"arabic_name" varchar(200),
	"code" varchar(20) NOT NULL,
	"description" varchar(1000),
	"arabic_description" varchar(1000),
	"color" varchar(20),
	"icon" varchar(50),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	CONSTRAINT "programs_name_unique" UNIQUE("name"),
	CONSTRAINT "programs_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"arabic_name" varchar(200),
	"code" varchar(20) NOT NULL,
	"description" varchar(1000),
	"arabic_description" varchar(1000),
	"program_id" integer,
	"color" varchar(20),
	"icon" varchar(50),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	CONSTRAINT "uq_projects_program_name" UNIQUE("program_id","name"),
	CONSTRAINT "uq_projects_program_code" UNIQUE("program_id","code")
);
--> statement-breakpoint
CREATE TABLE "cases" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"case_number" varchar(20) NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"category_id" integer NOT NULL,
	"priority_id" integer NOT NULL,
	"status_id" integer NOT NULL,
	"channel_id" integer NOT NULL,
	"case_date" timestamp with time zone DEFAULT now() NOT NULL,
	"due_date" timestamp with time zone,
	"resolved_date" timestamp with time zone,
	"impact_description" text,
	"urgency_level" "urgency_level",
	"affected_beneficiaries" integer,
	"program_id" integer,
	"project_id" integer,
	"activity_id" integer,
	"is_project_related" boolean DEFAULT false NOT NULL,
	"provider_type_id" integer,
	"individual_provider_gender" "provider_gender",
	"individual_provider_age_group" "provider_age_group",
	"individual_provider_disability_status" "provider_disability_status",
	"group_provider_size" integer,
	"group_provider_gender_composition" text,
	"provider_name" varchar(255),
	"provider_email" varchar(255),
	"provider_phone" varchar(50),
	"provider_organization" varchar(255),
	"provider_address" varchar(255),
	"data_sharing_consent" boolean DEFAULT false NOT NULL,
	"follow_up_consent" boolean DEFAULT false NOT NULL,
	"follow_up_contact_method" "follow_up_contact_method",
	"privacy_policy_accepted" boolean DEFAULT false NOT NULL,
	"is_sensitive" boolean DEFAULT false NOT NULL,
	"is_anonymized" boolean DEFAULT false NOT NULL,
	"is_public" boolean DEFAULT false NOT NULL,
	"confidentiality_level" "confidentiality_level" DEFAULT 'internal' NOT NULL,
	"community_id" integer,
	"location" varchar(255),
	"coordinates" varchar(50),
	"assigned_to" integer,
	"assigned_by" integer,
	"assigned_at" timestamp with time zone,
	"assignment_comments" text,
	"submitted_by" integer,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"submitted_by_initials" varchar(10),
	"submitted_by_confirmation" boolean,
	"submitted_by_comments" text,
	"first_response_date" timestamp with time zone,
	"last_activity_date" timestamp with time zone,
	"escalation_level" integer DEFAULT 0 NOT NULL,
	"escalated_at" timestamp with time zone,
	"escalated_by" integer,
	"escalation_reason" varchar(500),
	"resolution_summary" text,
	"resolution_category" "resolution_category",
	"resolution_satisfaction" "resolution_satisfaction",
	"tags" varchar(1000),
	"attachments" jsonb,
	"external_references" varchar(500),
	"follow_up_required" boolean DEFAULT false NOT NULL,
	"follow_up_date" timestamp with time zone,
	"monitoring_required" boolean DEFAULT false NOT NULL,
	"monitoring_date" timestamp with time zone,
	"quality_reviewed" boolean DEFAULT false NOT NULL,
	"quality_reviewed_by" integer,
	"quality_reviewed_at" timestamp with time zone,
	"quality_score" numeric(3, 2),
	"quality_comments" varchar(500),
	"embedding" vector(1024),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" integer,
	CONSTRAINT "cases_case_number_unique" UNIQUE("case_number")
);
--> statement-breakpoint
CREATE TABLE "case_assignments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "case_assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"case_id" integer NOT NULL,
	"assigned_to" integer NOT NULL,
	"assigned_by" integer NOT NULL,
	"assignment_type" "assignment_type" DEFAULT 'primary' NOT NULL,
	"assignment_reason" varchar(500),
	"comments" text,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expected_completion_date" timestamp with time zone,
	"actual_completion_date" timestamp with time zone,
	"assignment_status" "assignment_status" DEFAULT 'active' NOT NULL,
	"completion_comments" text,
	"workload_percentage" numeric(5, 2),
	"estimated_hours" numeric(8, 2),
	"actual_hours" numeric(8, 2),
	"transferred_to" integer,
	"transferred_by" integer,
	"transferred_at" timestamp with time zone,
	"transfer_reason" varchar(500),
	"escalated_to" integer,
	"escalated_by" integer,
	"escalated_at" timestamp with time zone,
	"escalation_level" integer DEFAULT 0 NOT NULL,
	"escalation_reason" varchar(500),
	"response_time" numeric(10, 2),
	"resolution_time" numeric(10, 2),
	"quality_score" numeric(3, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "case_attachments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "case_attachments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"case_id" integer NOT NULL,
	"file_name" varchar(255),
	"original_file_name" varchar(255),
	"file_path" varchar(1000),
	"file_size" bigint,
	"file_type" varchar(100),
	"file_extension" varchar(10),
	"attachment_type" "attachment_type" DEFAULT 'document' NOT NULL,
	"attachment_category" "attachment_category",
	"description" text,
	"confidentiality_level" "confidentiality_level",
	"encryption_status" "encryption_status" DEFAULT 'none' NOT NULL,
	"access_control" jsonb,
	"storage_provider" "storage_provider" DEFAULT 'b2' NOT NULL,
	"storage_location" varchar(1000),
	"checksum" varchar(128),
	"download_count" integer DEFAULT 0 NOT NULL,
	"last_downloaded_at" timestamp with time zone,
	"last_downloaded_by" integer,
	"virus_scan_status" "virus_scan_status" DEFAULT 'pending' NOT NULL,
	"virus_scan_date" timestamp with time zone,
	"virus_scan_result" text,
	"thumbnail_path" varchar(1000),
	"preview_path" varchar(1000),
	"has_preview" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" integer,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "case_comments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "case_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"case_id" integer NOT NULL,
	"comment" text NOT NULL,
	"comment_type" "comment_type" DEFAULT 'internal' NOT NULL,
	"is_internal" boolean DEFAULT true NOT NULL,
	"is_public" boolean DEFAULT false NOT NULL,
	"confidentiality_level" "confidentiality_level" DEFAULT 'internal' NOT NULL,
	"recipient_type" "recipient_type",
	"recipient_email" varchar(255),
	"communication_method" "communication_method",
	"communication_status" "communication_status",
	"attachments" jsonb,
	"attachment_count" integer DEFAULT 0 NOT NULL,
	"parent_comment_id" integer,
	"is_response" boolean DEFAULT false NOT NULL,
	"response_to_user_id" integer,
	"mentioned_users" jsonb,
	"tags" varchar(500),
	"requires_follow_up" boolean DEFAULT false NOT NULL,
	"follow_up_date" timestamp with time zone,
	"follow_up_completed" boolean DEFAULT false NOT NULL,
	"follow_up_completed_at" timestamp with time zone,
	"is_edited" boolean DEFAULT false NOT NULL,
	"edited_at" timestamp with time zone,
	"edited_by" integer,
	"edit_reason" varchar(500),
	"original_comment" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" integer,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "case_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "case_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"case_id" integer NOT NULL,
	"action_type" "case_history_action_type" NOT NULL,
	"field_name" varchar(100),
	"old_value" text,
	"new_value" text,
	"change_description" varchar(500),
	"comments" text,
	"assigned_to" integer,
	"assigned_by" integer,
	"assignment_comments" text,
	"status_id" integer,
	"status_reason" varchar(500),
	"ip_address" varchar(45),
	"user_agent" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"action" "audit_action" NOT NULL,
	"entity_type" "audit_entity_type",
	"entity_id" integer,
	"old_values" jsonb,
	"new_values" jsonb,
	"field_changes" jsonb,
	"ip_address" varchar(45),
	"user_agent" text,
	"request_method" "request_method",
	"request_url" text,
	"request_headers" jsonb,
	"success" boolean DEFAULT true NOT NULL,
	"error_message" text,
	"response_code" integer,
	"execution_time_ms" integer,
	"session_id" varchar(1000),
	"correlation_id" varchar(100),
	"risk_score" numeric(3, 2),
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"case_id" integer,
	"entity_type" "notification_entity_type",
	"entity_id" integer,
	"type" "notification_type" NOT NULL,
	"title" varchar(255),
	"message" text,
	"priority" "notification_priority" DEFAULT 'normal' NOT NULL,
	"action_url" varchar(500),
	"action_text" varchar(100),
	"is_read" boolean DEFAULT false NOT NULL,
	"read_at" timestamp with time zone,
	"is_email_sent" boolean DEFAULT false NOT NULL,
	"email_sent_at" timestamp with time zone,
	"email_error" text,
	"is_push_sent" boolean DEFAULT false NOT NULL,
	"push_sent_at" timestamp with time zone,
	"push_error" text,
	"metadata" jsonb,
	"trigger_user_id" integer,
	"trigger_action" varchar(100),
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "system_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "system_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"setting_key" varchar(100) NOT NULL,
	"setting_value" text,
	"setting_type" "setting_type" DEFAULT 'string' NOT NULL,
	"category" "setting_category" NOT NULL,
	"display_name" varchar(255) NOT NULL,
	"description" varchar(1000),
	"validation_rules" jsonb,
	"default_value" text,
	"is_public" boolean DEFAULT false NOT NULL,
	"is_encrypted" boolean DEFAULT false NOT NULL,
	"requires_restart" boolean DEFAULT false NOT NULL,
	"environment" "environment" DEFAULT 'all' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer,
	CONSTRAINT "system_settings_setting_key_unique" UNIQUE("setting_key")
);
--> statement-breakpoint
CREATE TABLE "user_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_token" varchar(1000) NOT NULL,
	"user_id" integer NOT NULL,
	"refresh_token" varchar(1000),
	"refresh_token_expires_at" timestamp with time zone,
	"ip_address" varchar(45),
	"user_agent" varchar(1000),
	"device_info" jsonb,
	"location" varchar(200),
	"expires_at" timestamp with time zone NOT NULL,
	"last_activity_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_revoked" boolean DEFAULT false NOT NULL,
	"revoked_at" timestamp with time zone,
	"revoked_by" integer,
	"revoke_reason" varchar(500),
	"session_type" "session_type" DEFAULT 'web' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "user_sessions_session_token_unique" UNIQUE("session_token")
);
--> statement-breakpoint
ALTER TABLE "communities" ADD CONSTRAINT "communities_governorate_id_governorates_id_fk" FOREIGN KEY ("governorate_id") REFERENCES "public"."governorates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "governorates" ADD CONSTRAINT "governorates_region_id_regions_id_fk" FOREIGN KEY ("region_id") REFERENCES "public"."regions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_program_id_programs_id_fk" FOREIGN KEY ("program_id") REFERENCES "public"."programs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_category_id_case_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."case_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_priority_id_case_priorities_id_fk" FOREIGN KEY ("priority_id") REFERENCES "public"."case_priorities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_status_id_case_statuses_id_fk" FOREIGN KEY ("status_id") REFERENCES "public"."case_statuses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_channel_id_case_channels_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."case_channels"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_program_id_programs_id_fk" FOREIGN KEY ("program_id") REFERENCES "public"."programs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_activity_id_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_provider_type_id_provider_types_id_fk" FOREIGN KEY ("provider_type_id") REFERENCES "public"."provider_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_community_id_communities_id_fk" FOREIGN KEY ("community_id") REFERENCES "public"."communities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_assigned_to_users_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_assigned_by_users_id_fk" FOREIGN KEY ("assigned_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_submitted_by_users_id_fk" FOREIGN KEY ("submitted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_escalated_by_users_id_fk" FOREIGN KEY ("escalated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_quality_reviewed_by_users_id_fk" FOREIGN KEY ("quality_reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_assignments" ADD CONSTRAINT "case_assignments_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_assignments" ADD CONSTRAINT "case_assignments_assigned_to_users_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_assignments" ADD CONSTRAINT "case_assignments_assigned_by_users_id_fk" FOREIGN KEY ("assigned_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_assignments" ADD CONSTRAINT "case_assignments_transferred_to_users_id_fk" FOREIGN KEY ("transferred_to") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_assignments" ADD CONSTRAINT "case_assignments_transferred_by_users_id_fk" FOREIGN KEY ("transferred_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_assignments" ADD CONSTRAINT "case_assignments_escalated_to_users_id_fk" FOREIGN KEY ("escalated_to") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_assignments" ADD CONSTRAINT "case_assignments_escalated_by_users_id_fk" FOREIGN KEY ("escalated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_attachments" ADD CONSTRAINT "case_attachments_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_attachments" ADD CONSTRAINT "case_attachments_last_downloaded_by_users_id_fk" FOREIGN KEY ("last_downloaded_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_comments" ADD CONSTRAINT "case_comments_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_comments" ADD CONSTRAINT "case_comments_parent_comment_id_case_comments_id_fk" FOREIGN KEY ("parent_comment_id") REFERENCES "public"."case_comments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_comments" ADD CONSTRAINT "case_comments_response_to_user_id_users_id_fk" FOREIGN KEY ("response_to_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_history" ADD CONSTRAINT "case_history_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_history" ADD CONSTRAINT "case_history_assigned_to_users_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_history" ADD CONSTRAINT "case_history_assigned_by_users_id_fk" FOREIGN KEY ("assigned_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "case_history" ADD CONSTRAINT "case_history_status_id_case_statuses_id_fk" FOREIGN KEY ("status_id") REFERENCES "public"."case_statuses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_trigger_user_id_users_id_fk" FOREIGN KEY ("trigger_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_revoked_by_users_id_fk" FOREIGN KEY ("revoked_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_users_email" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_users_username" ON "users" USING btree ("username");--> statement-breakpoint
CREATE INDEX "idx_users_role" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "idx_users_organization" ON "users" USING btree ("organization");--> statement-breakpoint
CREATE INDEX "idx_users_is_active" ON "users" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_users_is_deleted" ON "users" USING btree ("is_deleted");--> statement-breakpoint
CREATE INDEX "idx_users_email_verification_token" ON "users" USING btree ("email_verification_token");--> statement-breakpoint
CREATE INDEX "idx_users_password_reset_token" ON "users" USING btree ("password_reset_token");--> statement-breakpoint
CREATE INDEX "idx_users_last_login" ON "users" USING btree ("last_login");--> statement-breakpoint
CREATE INDEX "idx_users_created_at" ON "users" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_case_categories_name" ON "case_categories" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_case_categories_is_active" ON "case_categories" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_case_categories_sort_order" ON "case_categories" USING btree ("sort_order");--> statement-breakpoint
CREATE INDEX "idx_case_channels_name" ON "case_channels" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_case_channels_is_active" ON "case_channels" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_case_channels_sort_order" ON "case_channels" USING btree ("sort_order");--> statement-breakpoint
CREATE INDEX "idx_case_priorities_name" ON "case_priorities" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_case_priorities_level" ON "case_priorities" USING btree ("level");--> statement-breakpoint
CREATE INDEX "idx_case_priorities_is_active" ON "case_priorities" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_case_statuses_name" ON "case_statuses" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_case_statuses_is_active" ON "case_statuses" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_case_statuses_sort_order" ON "case_statuses" USING btree ("sort_order");--> statement-breakpoint
CREATE INDEX "idx_case_statuses_is_initial" ON "case_statuses" USING btree ("is_initial");--> statement-breakpoint
CREATE INDEX "idx_case_statuses_is_final" ON "case_statuses" USING btree ("is_final");--> statement-breakpoint
CREATE INDEX "idx_provider_types_name" ON "provider_types" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_provider_types_is_active" ON "provider_types" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_provider_types_sort_order" ON "provider_types" USING btree ("sort_order");--> statement-breakpoint
CREATE INDEX "idx_communities_governorate_id" ON "communities" USING btree ("governorate_id");--> statement-breakpoint
CREATE INDEX "idx_communities_is_active" ON "communities" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_governorates_region_id" ON "governorates" USING btree ("region_id");--> statement-breakpoint
CREATE INDEX "idx_governorates_is_active" ON "governorates" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_regions_name" ON "regions" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_regions_code" ON "regions" USING btree ("code");--> statement-breakpoint
CREATE INDEX "idx_regions_is_active" ON "regions" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_activities_project_id" ON "activities" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_activities_is_active" ON "activities" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_programs_name" ON "programs" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_programs_code" ON "programs" USING btree ("code");--> statement-breakpoint
CREATE INDEX "idx_programs_is_active" ON "programs" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_projects_program_id" ON "projects" USING btree ("program_id");--> statement-breakpoint
CREATE INDEX "idx_projects_is_active" ON "projects" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_cases_case_number" ON "cases" USING btree ("case_number");--> statement-breakpoint
CREATE INDEX "idx_cases_category_id" ON "cases" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "idx_cases_priority_id" ON "cases" USING btree ("priority_id");--> statement-breakpoint
CREATE INDEX "idx_cases_status_id" ON "cases" USING btree ("status_id");--> statement-breakpoint
CREATE INDEX "idx_cases_channel_id" ON "cases" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "idx_cases_assigned_to" ON "cases" USING btree ("assigned_to");--> statement-breakpoint
CREATE INDEX "idx_cases_submitted_by" ON "cases" USING btree ("submitted_by");--> statement-breakpoint
CREATE INDEX "idx_cases_community_id" ON "cases" USING btree ("community_id");--> statement-breakpoint
CREATE INDEX "idx_cases_program_id" ON "cases" USING btree ("program_id");--> statement-breakpoint
CREATE INDEX "idx_cases_case_date" ON "cases" USING btree ("case_date");--> statement-breakpoint
CREATE INDEX "idx_cases_due_date" ON "cases" USING btree ("due_date");--> statement-breakpoint
CREATE INDEX "idx_cases_confidentiality_level" ON "cases" USING btree ("confidentiality_level");--> statement-breakpoint
CREATE INDEX "idx_cases_is_sensitive" ON "cases" USING btree ("is_sensitive");--> statement-breakpoint
CREATE INDEX "idx_cases_is_deleted" ON "cases" USING btree ("is_deleted");--> statement-breakpoint
CREATE INDEX "idx_cases_is_active" ON "cases" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_cases_created_at" ON "cases" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_case_assignments_case_id" ON "case_assignments" USING btree ("case_id");--> statement-breakpoint
CREATE INDEX "idx_case_assignments_assigned_to" ON "case_assignments" USING btree ("assigned_to");--> statement-breakpoint
CREATE INDEX "idx_case_assignments_status" ON "case_assignments" USING btree ("assignment_status");--> statement-breakpoint
CREATE INDEX "idx_case_attachments_case_id" ON "case_attachments" USING btree ("case_id");--> statement-breakpoint
CREATE INDEX "idx_case_attachments_is_deleted" ON "case_attachments" USING btree ("is_deleted");--> statement-breakpoint
CREATE INDEX "idx_case_comments_case_id" ON "case_comments" USING btree ("case_id");--> statement-breakpoint
CREATE INDEX "idx_case_comments_parent" ON "case_comments" USING btree ("parent_comment_id");--> statement-breakpoint
CREATE INDEX "idx_case_comments_is_deleted" ON "case_comments" USING btree ("is_deleted");--> statement-breakpoint
CREATE INDEX "idx_case_comments_created_at" ON "case_comments" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_case_history_case_id" ON "case_history" USING btree ("case_id");--> statement-breakpoint
CREATE INDEX "idx_case_history_action_type" ON "case_history" USING btree ("action_type");--> statement-breakpoint
CREATE INDEX "idx_case_history_created_at" ON "case_history" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_case_history_created_by" ON "case_history" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_action" ON "audit_logs" USING btree ("action");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_created_at" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_notifications_user_id" ON "notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_notifications_case_id" ON "notifications" USING btree ("case_id");--> statement-breakpoint
CREATE INDEX "idx_notifications_type" ON "notifications" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_notifications_is_read" ON "notifications" USING btree ("is_read");--> statement-breakpoint
CREATE INDEX "idx_notifications_created_at" ON "notifications" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_system_settings_key" ON "system_settings" USING btree ("setting_key");--> statement-breakpoint
CREATE INDEX "idx_system_settings_category" ON "system_settings" USING btree ("category");--> statement-breakpoint
CREATE INDEX "idx_user_sessions_user_id" ON "user_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_user_sessions_expires_at" ON "user_sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_user_sessions_is_revoked" ON "user_sessions" USING btree ("is_revoked");